#!/bin/sh
# install.sh — Booki one-liner installer.
#
# Usage:
#   curl -sSfL https://raw.githubusercontent.com/barakbl/booki/main/install/install.sh | sh
#
# Goals:
#   - Idempotent: re-running pulls the latest code, refreshes the venv,
#     and re-applies shell snippets without duplicating lines.
#   - XDG-compliant: code under $XDG_DATA_HOME/booki, config under
#     $XDG_CONFIG_HOME/booki, wrapper under $XDG_BIN_HOME (or PATH-y
#     equivalent for whichever shell you run).
#   - Self-contained: creates its own virtualenv, never touches system Python.
#   - Friendly: detects fish / zsh / bash and adds the right snippet to
#     the right rc file. Suggests brew / apt / dnf / pacman commands for
#     optional binaries (ffmpeg, fzf, ollama, …) at the end.
#
# Heads-up: this is the *less recommended* install path. Booki is a small,
# editable, hackable project — you're meant to read and tweak it. The
# `git clone + cd booki` flow gives you the working tree this project is
# designed around. The installer is here for users who just want to try
# Booki without the venv ceremony.

set -e

# ─── parameters ─────────────────────────────────────────────────────────────

REPO=${BOOKI_REPO:-https://github.com/barakbl/booki.git}
BRANCH=${BOOKI_BRANCH:-main}

XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
XDG_BIN_HOME=${XDG_BIN_HOME:-$HOME/.local/bin}

BOOKI_HOME=$XDG_DATA_HOME/booki
CONFIG_DIR=$XDG_CONFIG_HOME/booki
VENV=$BOOKI_HOME/.venv

# ─── pretty output ──────────────────────────────────────────────────────────

if [ -t 1 ]; then
    NC=$(printf '\033[0m'); BOLD=$(printf '\033[1m')
    G=$(printf '\033[32m'); Y=$(printf '\033[33m')
    R=$(printf '\033[31m'); B=$(printf '\033[36m')
else
    NC=""; BOLD=""; G=""; Y=""; R=""; B=""
fi

say()  { printf '\n%s▸ %s%s\n'  "$B"   "$1" "$NC"; }
ok()   { printf '%s  ✓%s %s\n'  "$G"   "$NC" "$1"; }
warn() { printf '%s  ⚠%s %s\n'  "$Y"   "$NC" "$1"; }
err()  { printf '%s  ✗%s %s\n'  "$R"   "$NC" "$1" >&2; }
die()  { err "$1"; exit 1; }

# ─── prereqs ────────────────────────────────────────────────────────────────

need() {
    if ! command -v "$1" >/dev/null 2>&1; then
        die "missing required tool: $1 (install it and re-run)"
    fi
}

say "Checking prerequisites"
need git
need python3
need curl

PY_VERSION=$(python3 -c 'import sys; print("%d.%d" % sys.version_info[:2])')
case "$PY_VERSION" in
    3.10|3.11|3.12|3.13|3.14|3.15) ok "python $PY_VERSION" ;;
    *) die "python ≥ 3.10 required (found $PY_VERSION)" ;;
esac

mkdir -p "$XDG_DATA_HOME" "$XDG_CONFIG_HOME" "$XDG_BIN_HOME" "$CONFIG_DIR"

# ─── clone or update ────────────────────────────────────────────────────────

say "Source tree at $BOOKI_HOME"
if [ -d "$BOOKI_HOME/.git" ]; then
    git -C "$BOOKI_HOME" fetch --quiet origin "$BRANCH"
    git -C "$BOOKI_HOME" reset --hard --quiet "origin/$BRANCH"
    ok "updated to origin/$BRANCH ($(git -C "$BOOKI_HOME" rev-parse --short HEAD))"
elif [ -e "$BOOKI_HOME" ]; then
    die "$BOOKI_HOME exists but is not a git checkout. Move it aside or delete it."
else
    git clone --quiet --branch "$BRANCH" "$REPO" "$BOOKI_HOME"
    ok "cloned $REPO → $BOOKI_HOME"
fi

# ─── venv + dependencies ────────────────────────────────────────────────────

say "Python virtualenv at $VENV"
if [ ! -d "$VENV" ]; then
    python3 -m venv "$VENV"
    ok "created"
else
    ok "reused existing"
fi

"$VENV/bin/pip" install --quiet --upgrade pip
"$VENV/bin/pip" install --quiet -r "$BOOKI_HOME/requirements.txt"
ok "dependencies up to date"

# ─── config ─────────────────────────────────────────────────────────────────

say "Configuration"
if [ ! -f "$CONFIG_DIR/config.toml" ]; then
    cp "$BOOKI_HOME/config.toml.example" "$CONFIG_DIR/config.toml"
    ok "wrote $CONFIG_DIR/config.toml from example"
else
    ok "kept existing $CONFIG_DIR/config.toml"
fi

# Symlink the install dir's expected config.toml at the XDG config so the
# dispatcher's default path resolution finds it. Re-create the link every
# run so the target stays correct after a moved $XDG_CONFIG_HOME.
ln -sfn "$CONFIG_DIR/config.toml" "$BOOKI_HOME/config.toml"
ok "linked $BOOKI_HOME/config.toml → $CONFIG_DIR/config.toml"

# ─── wrapper ────────────────────────────────────────────────────────────────

say "Dispatcher wrapper"
WRAPPER=$XDG_BIN_HOME/booki
cat > "$WRAPPER" <<EOF
#!/bin/sh
# Booki dispatcher — generated by install.sh; safe to overwrite by re-running.
# Runs the venv-bound python on the in-tree dispatcher script so the
# system Python is never touched.
exec "$VENV/bin/python" "$BOOKI_HOME/booki" "\$@"
EOF
chmod +x "$WRAPPER"
ok "wrote $WRAPPER"

# ─── manager sidecar (optional) ─────────────────────────────────────────────
#
# Builds tools/booki-manager (Rust). Cargo is optional — if it's missing the
# rest of Booki installs cleanly and we just emit a hint. Re-running is
# safe: `cargo build --release` is incremental and the wrapper is rewritten
# in place.

say "Manager sidecar"
MGR_SRC=$BOOKI_HOME/tools/booki-manager
MGR_BIN=$MGR_SRC/target/release/booki-manager
MGR_WRAPPER=$XDG_BIN_HOME/booki-manager

if [ ! -d "$MGR_SRC" ]; then
    warn "tools/booki-manager not present in checkout — skipping"
elif ! command -v cargo >/dev/null 2>&1; then
    warn "cargo missing — skipping manager build"
    warn "  install Rust toolchain to enable: https://rustup.rs/"
else
    ( cd "$MGR_SRC" && cargo build --release --quiet )
    if [ ! -x "$MGR_BIN" ]; then
        die "cargo build did not produce $MGR_BIN"
    fi
    ok "built $MGR_BIN"

    # Generated wrapper pins BOOKI_HOME so the manager finds config.toml + the
    # ./booki entrypoint regardless of cwd at launch time.
    cat > "$MGR_WRAPPER" <<EOF
#!/bin/sh
# booki-manager wrapper — generated by install.sh; safe to overwrite.
exec env BOOKI_HOME="$BOOKI_HOME" "$MGR_BIN" "\$@"
EOF
    chmod +x "$MGR_WRAPPER"
    ok "wrote $MGR_WRAPPER"
fi

# ─── shell integration (idempotent) ─────────────────────────────────────────

# Append `line` to `file` only if it isn't already a literal line in the file.
idem_append() {
    file=$1; line=$2; tag=$3
    mkdir -p "$(dirname "$file")"
    [ -f "$file" ] || : > "$file"
    if grep -F -x -- "$line" "$file" >/dev/null 2>&1; then
        ok "$file already has $tag"
    else
        printf '\n# Added by booki installer\n%s\n' "$line" >> "$file"
        ok "added $tag to $file"
    fi
}

detect_shell() {
    case "${SHELL:-}" in
        */fish) echo fish ;;
        */zsh)  echo zsh ;;
        */bash) echo bash ;;
        *)      echo "" ;;
    esac
}

say "Shell integration"
SH=$(detect_shell)
case "$SH" in
    fish)
        FISH_RC=$XDG_CONFIG_HOME/fish/config.fish
        idem_append "$FISH_RC" "fish_add_path -g $XDG_BIN_HOME" "PATH"
        if [ -f "$BOOKI_HOME/shells/booki.fish" ]; then
            idem_append "$FISH_RC" "source $BOOKI_HOME/shells/booki.fish" "completions"
        fi
        ;;
    zsh)
        ZRC=$HOME/.zshrc
        idem_append "$ZRC" "export PATH=\"$XDG_BIN_HOME:\$PATH\"" "PATH"
        if [ -f "$BOOKI_HOME/shells/booki.zsh" ]; then
            idem_append "$ZRC" "source $BOOKI_HOME/shells/booki.zsh" "completions"
        fi
        ;;
    bash)
        BRC=$HOME/.bashrc
        case "$(uname -s)" in Darwin) BRC=$HOME/.bash_profile ;; esac
        idem_append "$BRC" "export PATH=\"$XDG_BIN_HOME:\$PATH\"" "PATH"
        ;;
    *)
        warn "Could not detect your shell. Add $XDG_BIN_HOME to PATH manually."
        ;;
esac

# ─── optional binaries ──────────────────────────────────────────────────────

say "Optional dependencies"
suggest() {
    pkg=$1; mac=$2; deb=$3; arch=$4; rh=$5
    if command -v "$pkg" >/dev/null 2>&1; then
        ok "$pkg already installed"
        return
    fi
    case "$(uname -s)" in
        Darwin)
            if command -v brew >/dev/null 2>&1; then
                warn "$pkg missing — recommended:  brew install $mac"
            else
                warn "$pkg missing — install Homebrew, then: brew install $mac"
            fi
            ;;
        Linux)
            if command -v apt >/dev/null 2>&1; then
                [ -n "$deb" ] && warn "$pkg missing — recommended:  sudo apt install $deb"
            elif command -v dnf >/dev/null 2>&1; then
                [ -n "$rh" ] && warn "$pkg missing — recommended:  sudo dnf install $rh"
            elif command -v pacman >/dev/null 2>&1; then
                [ -n "$arch" ] && warn "$pkg missing — recommended:  sudo pacman -S $arch"
            else
                warn "$pkg missing (your package manager wasn't detected)"
            fi
            ;;
        *)
            warn "$pkg missing"
            ;;
    esac
}

suggest ffmpeg ffmpeg ffmpeg ffmpeg ffmpeg
suggest fzf    fzf    fzf    fzf    fzf
suggest ollama ollama ""     ollama-bin ollama   # local LLM (optional)

# ─── done ───────────────────────────────────────────────────────────────────

cat <<EOF

${BOLD}Booki installed.${NC}

  Code      : $BOOKI_HOME
  Venv      : $VENV
  Config    : $CONFIG_DIR/config.toml
  Wrapper   : $WRAPPER
EOF
if [ -x "$MGR_WRAPPER" ]; then
cat <<EOF
  Manager   : $MGR_WRAPPER
EOF
fi
cat <<EOF

Open a fresh shell (or 'source' your rc file) and try:

  booki doctor          # check the install
  booki sync            # pull from sources
  booki ingest          # build the vector index
  booki web             # browse in your browser
EOF
if [ -x "$MGR_WRAPPER" ]; then
cat <<EOF
  booki-manager         # menubar app: watches bookmarks + scheduled sync/ingest
EOF
fi
cat <<EOF

Re-run this installer any time to update — it's idempotent and only
fast-forwards origin/$BRANCH.
EOF
